<a href="https://colab.research.google.com/github/SPThole/pyTrch/blob/master/Playing_around_with_torchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#installing pytorch
!pip install torch

Learning Pytorch, first of all lets understand the tensors.

In [2]:
#importing necessary libraries
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt


In [4]:
#creating some tensors: https://stackoverflow.com/questions/51911749/what-is-the-difference-between-torch-tensor-and-torch-tensor
x= torch.tensor([1,2,3])
y= torch.tensor([2,4,6])

In [17]:
#similar to numpy arrays we can even check the shapes of the tesnors using shape method
x.shape, y.shape


(torch.Size([2, 2]), torch.Size([2, 2]))

In [6]:
#We can create tensors using directly passing values to it 
z= torch.Tensor([[[1,2,3],[2,3,4]],[[6,7,8],[8,9,10]]])

In [7]:
z.shape

torch.Size([2, 2, 3])

In [8]:
#if we want just a number from the scalar we can get it by item()
torch.Tensor([3]).item()

3.0

In [9]:
#adding two tensors
res= torch.empty([2,2])
print(res)
x= torch.rand([2,2])
y= torch.rand([2,2])
res=x+y
print(res,x,y)

tensor([[3.8343e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00]])
tensor([[1.0537, 0.8975],
        [0.5860, 1.0101]]) tensor([[0.6637, 0.1115],
        [0.2167, 0.2834]]) tensor([[0.3900, 0.7860],
        [0.3693, 0.7267]])


In [10]:
#just like np.ones and np.zeros
o= torch.ones([2,2])
print(o)
z= torch.zeros([2,3,3])
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
#istead of using expression we can directly add 
torch.add(x,y,out=res)

tensor([[1.0537, 0.8975],
        [0.5860, 1.0101]])

In [12]:
#matmul
torch.matmul(torch.ones([3,2]),torch.rand([2,2]))

tensor([[1.3873, 1.1677],
        [1.3873, 1.1677],
        [1.3873, 1.1677]])

In [13]:
#absolute |x|
torch.absolute(-1*torch.ones([2,2]))

tensor([[1., 1.],
        [1., 1.]])

In [14]:
#we is kind of similar to the reshape, we can even use reshape instead of view
torch.rand([3,4]).view(-1,6)


tensor([[0.0094, 0.9494, 0.0566, 0.8164, 0.2680, 0.0942],
        [0.1113, 0.0768, 0.4619, 0.4130, 0.5787, 0.3251]])

In [15]:
#We can conver numpy array to tensor
np_array= np.ones([2,2])
torch_tensor= torch.from_numpy(np_array)
type(torch_tensor)

torch.Tensor

In [16]:
#and can also convert to ndarray
back_to_array= torch_tensor.numpy()
type(back_to_array)

numpy.ndarray